CREATE OR REPLACE FUNCTION EJ10 (V_NUM1 IN NUMBER, V_NUM2 IN NUMBER, V_NUM3 IN NUMBER)
RETURN NUMBER IS
V_AUX1 NUMBER(4) := V_NUM1;
V_AUX2 NUMBER(4) := V_NUM2;
V_AUX3 NUMBER(4) := V_NUM3;
V_MAX NUMBER(4);
BEGIN
SELECT GREATEST(V_AUX1,V_AUX2,V_AUX3) INTO V_MAX FROM DUAL;
RETURN V_MAX;
END;
