CREATE OR REPLACE FUNCTION EJ5_2  
RETURN NUMBER IS
V_NUMEMPELADOS NUMBER(3);
BEGIN
SELECT COUNT(*) INTO V_NUMEMPELADOS FROM EMPLEADOS WHERE ID_DEPARTAMENTO = (SELECT ID_DEPARTAMENTO FROM DEPARTAMENTO WHERE NOMBRE = 'Personal');
RETURN V_NUMEMPELADOS;
END;
SELECT EJ6 FROM DUAL;
