CREATE OR REPLACE FUNCTION EJ5_3 (V_DEPTO IN VARCHAR2)  
RETURN NUMBER IS
V_NOMBREDEPTO VARCHAR2(100) := V_DEPTO;
V_NUMEMPELADOS NUMBER(3);
BEGIN
SELECT COUNT(*) INTO V_NUMEMPELADOS FROM EMPLEADOS WHERE ID_DEPARTAMENTO = (SELECT ID_DEPARTAMENTO FROM DEPARTAMENTO WHERE NOMBRE = V_NOMBREDEPTO);
RETURN V_NUMEMPELADOS;
END;
