CREATE OR REPLACE PROCEDURE EJ5(
V_CODEMPLEADO  VARCHAR2)IS
V_DNI VARCHAR(9);
BEGIN
SELECT DNI INTO V_DNI FROM DATOSPERSONALES WHERE CLAVE_EMPLEADO = V_CODEMPLEADO;
    DBMS_OUTPUT.PUT_LINE(V_DNI);
END;
CALL EJ5('EMP03');
