CREATE OR REPLACE FUNCTION EJ7 (V_NUM IN NUMBER)
RETURN VARCHAR IS
V_NUMERO NUMBER(4) := V_NUM;
V_FALSOBOOLEANO VARCHAR(5):='FALSE';
BEGIN
IF MOD(V_NUMERO,2)=0 THEN
V_FALSOBOOLEANO := 'TRUE';
END IF;
RETURN V_FALSOBOOLEANO;
END;
