CREATE OR REPLACE FUNCTION EJ8 (V_DIANUM IN NUMBER)
RETURN VARCHAR IS
V_NUM NUMBER(1) := V_DIANUM;
TYPE VA_DIAS IS VARRAY(7) OF VARCHAR(30);
V_DIAS VA_DIAS := VA_DIAS('LUNES','MARTES','MIERCOLES','JUEBES','VIERNES','SABADO','DOMINGO');
V_AUX VARCHAR(30);
BEGIN
V_AUX := V_DIAS(V_NUM);
RETURN V_AUX;
END;
