CREATE OR REPLACE PROCEDURE EJ12(
V_NOMBRE_DEPTO IN VARCHAR2) IS
V_DEPTO VARCHAR2(30) := V_NOMBRE_DEPTO;
V_FECHA_ALTA DATE;
V_OK VARCHAR(2) := 'OK';
BEGIN
SELECT MAX(FECHA_ALTA) INTO V_FECHA_ALTA FROM EMPLEADOS, DATOSPERSONALES, DEPARTAMENTO 
    WHERE ID_EMPLEADO = CLAVE_EMPLEADO 
    AND DEPARTAMENTO.ID_DEPARTAMENTO = EMPLEADOS.ID_DEPARTAMENTO
    AND DEPARTAMENTO.ID_DEPARTAMENTO = (SELECT ID_DEPARTAMENTO FROM DEPARTAMENTO WHERE NOMBRE = V_DEPTO);
UPDATE DATOSPERSONALES SET FECHA_ALTA = CURRENT_DATE WHERE FECHA_ALTA = V_FECHA_ALTA;
DBMS_OUTPUT.PUT_LINE(V_OK);
END;
